# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/alecthomas/participle"
  version = "0.2.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/dop251/goja"

[[constraint]]
  branch = "master"
  name = "github.com/dop251/goja_nodejs"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/atomicfile"

[[constraint]]
  name = "github.com/gammazero/nexus"
  version = "2.1.0"

[[constraint]]
  name = "github.com/ipfs/go-log"
  version = "1.5.7"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "6.0.29"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "2.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-net"
  version = "3.0.15"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  version = "2.4.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  version = "2.0.6"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mr-tron/base58"
  version = "1.1.0"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "1.4.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/shibukawa/configdir"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/go-logging"

[prune]
  go-tests = true
  unused-packages = true
