name: Update documentation

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OCP code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
        path: 'ocp'

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Build documentation tool
      run: |
        cd ocp/docs
        go build

    - name: Generate documentation
      run: |
        cd ocp/docs
        ./docs

    - name: Checkout documentation
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
        repository: 'OpenCollaborationPlatform/Documentation'
        ref: 'main'
        path: 'documentation' 
        
    - name: Copy over the docs folder
      run: |
        mkdir -p documentation/docs/source/ocpsource
        cp ocp/docs/ocpsource/*.rst documentation/docs/source/ocpsource
        mkdir -p documentation/docs/ext
        cp ocp/docs/ext/*.py documentation/docs/ext
        cp ocp/docs/index.rst -T documentation/docs/source/node.rst
    
    - name: Commit changes
      working-directory: ./documentation
      run: |
          git config user.name documentation-bot
          git config user.email bot@ocp.com
          cd docs
          git add .
          git commit -a -m "Autogenerated documentation update from OCP repository"
   
    - name: Push to github
      working-directory: ./documentation
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_API_TOKEN }}
        branch: 'main'
